---
title: Llunio elips
hero_image: images/banner.png
description: Llunio elips wrth brosesu gyda Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Cyflwyniad

