---
title: Zeichne eine Ellipse
hero_image: images/banner.png
description: Zeichne eine Ellipse in Processing mit Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Einleitung

