---
title: Desenhe uma elipse
hero_image: images/banner.png
description: Desenhe uma elipse utilizando Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Introdução

