---
title: Narysuj elipsę
hero_image: images/banner.png
description: Narysuj elipsę za pomocą przetwarzania w Pythonie
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Wprowadzenie

