---
title: Dessiner une ellipse
hero_image: images/banner.png
description: Dessiner une ellipse en utilisant Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Introduction

