---
title: Disegna un'ellisse
hero_image: images/banner.png
description: Disegna un'ellisse in processing con Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Introduzione

